title: Bugzilla
email: developers@bugzilla.org
description: ""
baseurl: ""
url: ""

sass:
  sass_dir: _sass

markdown: kramdown
plugins:
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
